### PR TITLE
Implemented loading of subregion

### PR DESCRIPTION
**Pull request by Tom-TBT**
Hello,
I wanted to be able to load subregions from my images (defined by ROIs in OMERO in my case), so here is my attempt for the implementation.

I made it so that the same function `getImage` is used, and subregion is an optional parameter.
I specify the coordinates in a string, that is parsed with a regex.

Range of the coordinates can be passed like so:
* `z:10:20` -> Z from 10 (incl) to 20 (excl)
* `z:10:` -> From slice 10 and on
* `z::10` -> Up to slice 10
* `z:10` -> Slice 10 only

The coordinate in the string are 0 indexed (so that I don't have a mix of XY in 0-index and CZT in 1-index). It became useful when reusing them as an "offset" for the upload of ROIs made from within those subregions.

I included two template macros:
* One to load subregions from ROIs on OMERO (with a tiny hack of opening a fake image first)
* One to upload ROIs of that subregions. IMPORTANT NOTE: it needs ImageJ 1.54g or higher (I had to update the ImageJ of a freshly downloaded Fiji). 

Also, I haven't complied javadoc (I get some errors, most likely from my setup), and I haven't run the tests (test image on my OMERO would have different IDs , etc). But I will add test functions soon.

Thank you for reviewing and let me know if there is anything to change / improve!

Tom

### CODE REVIEW

**Comment by Tom-TBT** [comment]
Sorry for the failed first try, I fixed the failed test and added two other for this functionality

**Comment by Tom-TBT** [comment]
Hello hello,
here's my daily request for running new checks =)
 I added more tests to cover the code changes .

It's assuming that the image loaded (ID:1) is the same that is found in the code: 
`8bit-unsigned&pixelType=uint8&sizeZ=3&sizeC=5&sizeT=7&sizeX=512&sizeY=512.fake`
So XYCZT: 512 x 512 x 5 x 3 x 7

If not, please let me know what the image tested is like.

**Comment by ppouchin** [comment]
Thank you for your submissions. 
I'm sorry for being slow, I barely have time to click "approve and run" these days.
I'll check it thoroughly ASAP.

**Comment by ppouchin** [comment]
As for your question, the test data is initialized here: https://github.com/GReD-Clermont/omero_macro-extensions/blob/main/.omeroci/test-data
So image with ID=1 should be "image1.fake". 

I don't know if you managed to run the tests on your side.
If not, then FYI, they are run automatically through Docker using [omero-test-infra](https://github.com/ome/omero-test-infra?tab=readme-ov-file#setup): clone it to the project root with `git clone https://github.com/openmicroscopy/omero-test-infra .omero`
Then you need Docker (and Windows Subsystem for Linux (WSL) if you're on Windows).

To start the tests, I use this script from in Bash prompt, from the project root:
```bash
#!/bin/sh

export DOCKER_ARGS="-v $HOME/.m2:/root/.m2 -v $(pwd)/target:/src/target -t"
.omero/lib-docker
```

**Comment by Tom-TBT** [comment]
Hello Pierre,
thank you for the tips on testing, I will give it a go.

Let me know once after you got the time to test it.

**Comment by Tom-TBT** [comment]
Hello Pierre,
I was able to run the test with omero-test-infra, thanks for the help. 
With that I added a few more tests on the bounds possible inputs.

**Comment by Tom-TBT** [comment]
Hello Pierre,
have you had some time to test the open PRs? 

Writing this, I remember that I wanted to add an example macro with the key-value pairs. 
So you can expect a second notification soon ;)

**Pull request merged**
